# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-07 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persondynamic',
            old_name='person_id',
            new_name='person_static_id',
        ),
    ]
