# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-10 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170607_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persondynamic',
            old_name='person_static_id',
            new_name='person_static',
        ),
    ]
