# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-25 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20170610_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondynamic',
            name='citizenship_status',
        ),
        migrations.AlterField(
            model_name='persondynamic',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='The date and time on which this record expired', null=True, verbose_name='Record end date'),
        ),
        migrations.AlterField(
            model_name='personstatic',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='The date and time on which this record expired', null=True, verbose_name='Record end date'),
        ),
    ]
