# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-09 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20170625_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='addr_electronic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr_type', models.TextField(help_text='What kind of address - email, phone...', verbose_name='Address Type')),
                ('name', models.TextField(blank=True, help_text='Name of this address. e.g. home, work...', verbose_name='Address Name')),
                ('value', models.TextField(help_text='The actual electronic address', verbose_name='Address')),
                ('display_seq', models.IntegerField(help_text='The order in which this address should appear in lists', verbose_name='Display Sequence')),
                ('current_record_fg', models.BooleanField(default=True, help_text='Set to True for the current version of the record', verbose_name='Current record flag')),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now, help_text='The date & time on which this record became active', verbose_name='Record effective date')),
                ('end_date', models.DateTimeField(blank=True, help_text='The date and time on which this record expired', null=True, verbose_name='Record end date')),
                ('person_dynamic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.PersonDynamic', verbose_name='The related contact')),
            ],
        ),
    ]
