# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-09 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_addr_electronic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addr_electronic',
            new_name='AddrElectronic',
        ),
    ]
