# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-19 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20170709_1945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addrelectronic',
            options={'ordering': ['addr_type', 'display_seq']},
        ),
        migrations.RemoveField(
            model_name='addrelectronic',
            name='person_dynamic',
        ),
        migrations.AddField(
            model_name='addrelectronic',
            name='person_static',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.PersonStatic', verbose_name='The related contact'),
        ),
        migrations.AlterField(
            model_name='addrelectronic',
            name='addr_type',
            field=models.TextField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('Twitter', 'Twitter'), ('URL', 'URL'), ('Facebook', 'Facebook'), ('Other', 'Other')], help_text='What kind of address - email, phone...', verbose_name='Address Type'),
        ),
        migrations.AlterField(
            model_name='addrelectronic',
            name='name',
            field=models.TextField(blank=True, help_text='Name of this address. e.g. home, work...', verbose_name='E Address Name'),
        ),
    ]
